import assert from "node:assert";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const read = (p: string) => readFileSync(join(root, p), "utf8");
const migration = read("supabase/migrations/0011_slip_verification.sql");
const route = read("src/app/api/pay/[token]/slip/route.ts");
const confirm = read("src/lib/payments/slip/confirm.ts");
const successPage = read("src/app/booking/success/page.tsx");
const orderRoute = read("src/app/api/pay/[token]/order/route.ts");
const env = read("src/lib/env.ts");

assert.match(migration, /^begin;[\s\S]*commit;\s*$/m, "0011 is an atomic migration");
assert.match(migration, /create table if not exists public\.payment_transactions/);
assert.match(migration, /create unique index if not exists payment_transactions_provider_ref_uniq[\s\S]*?\(provider, normalized_tx_ref\)/);
assert.match(migration, /v_tx_ref := upper\(regexp_replace/);
assert.match(migration, /p_transfer_at < v_order\.created_at[\s\S]*?p_transfer_at > least\(v_order\.expires_at, v_booking\.hold_expires_at\)/);
assert.match(migration, /now\(\) >= v_order\.expires_at/);
assert.match(migration, /resolution = 'manual_review'/);
assert.match(migration, /p_provider <> 'promptpay_slip'/);
assert.match(migration, /p_currency <> v_order\.currency or v_order\.currency <> 'THB'/);
assert.match(migration, /p_receiver_profile is distinct from v_order\.receiver_profile/);
assert.match(migration, /payment_order_trust_fields_immutable/);
assert.match(migration, /before update of booking_id, provider, currency, amount_satang, receiver_profile/);
assert.match(migration, /create or replace function public\.approve_manual_review_payment/);
assert.match(migration, /resolution_reason = 'manual_approved'/);
assert.match(migration, /revoke all on function public\.confirm_slip_payment[\s\S]*?from public, anon, authenticated/);
assert.match(migration, /grant execute on function public\.confirm_slip_payment[\s\S]*?to service_role/);
assert.match(migration, /line_retry_key uuid default gen_random_uuid\(\)/);
assert.match(migration, /drop function if exists public\.claim_team_notification_deliveries/);
assert.match(migration, /line_retry_key uuid/);
assert.doesNotMatch(migration, /'customer', 'payment_confirmed'/);
assert.doesNotMatch(successPage, /getOrCreateSlipPaymentOrder/, "GET/render must not create orders");
assert.match(successPage, /slipOrderUrl = `\/api\/pay\/\$\{token\}\/order`/);
assert.match(successPage, /slipCfg\.enabled/);
assert.match(orderRoute, /!cfg\.enabled/);
assert.match(route, /receiverProfile: receiverMatches/);
assert.match(route, /!cfg\.enabled/);
assert.match(confirm, /p_currency: opts\.slip\.currency/);
assert.doesNotMatch(confirm, /p_currency: "THB"/);
assert.match(confirm, /slipVerificationEnabled\(\)/);
assert.match(env, /SLIP_VERIFICATION_ENABLED[\s\S]*?SLIP_VERIFICATION_PROVIDER[\s\S]*?easyslip_v2/);
console.log("slip-confirm self-check passed");
